In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random
import pickle
import os

In [2]:
from tensorflow import keras
model = keras.models.load_model('C:/Users/Asus/Documents/suyog/7th sem/ML mini/mlminimodel')

In [3]:
x_test = pickle.load(open('feature_gray_test.pkl','rb'))
y_test = pickle.load(open('label_gray_test.pkl','rb'))

In [4]:
(unique, counts) = np.unique(y_test, return_counts=True)
frequencies = np.asarray((unique, counts)).T
frequencies

array([[  0, 199],
       [  1, 225],
       [  2,  76]], dtype=int64)

In [5]:
x_test = np.array(x_test)

In [6]:
x_test = x_test/255

In [7]:
y_test = np.array(y_test)
x_test = x_test.reshape(-1,100,100,1)

In [8]:
predictions = model.predict(x_test)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [9]:

new_predicted_value = []
for i in range(500):
    predicted = np.argmax(predictions[i])
    new_predicted_value.append(predicted)

In [10]:
from sklearn import metrics

In [11]:

confusion_matrix = metrics.confusion_matrix(y_test, new_predicted_value, labels=[0, 1, 2])

In [12]:
print(confusion_matrix)

[[189   8   2]
 [ 15 202   8]
 [  3   2  71]]


In [13]:
accuracy = (confusion_matrix[0,0] + confusion_matrix[1,1] +confusion_matrix[2,2])/5  

In [14]:
print(accuracy)

92.4
